#
# algolia-search.yml
#
# Create a search index for Algolia Search when code is pushed to main.
#

name: Algolia-Search

on:
  push:
    branches:
      - main
  workflow_dispatch: {}
jobs:
  wait-for-vercel:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 300s
        shell: bash
  algolia-search:
    runs-on: ubuntu-latest
    needs: [wait-for-vercel]
    steps:
      - uses: actions/checkout@v2
      - name: Run algolia/docsearch-scraper
        run: |
          docker pull algolia/docsearch-scraper
          docker run \
            -e ALGOLIA_APP_ID=${{ secrets.ALGOLIA_APP_ID }} \
            -e API_KEY=${{ secrets.ALGOLIA_ADMIN_API_KEY }} \
            -e "CONFIG=$(cat ./algolia-config.json | jq -r tostring)" \
            algolia/docsearch-scraper
